export const Envs = {
  NEXTJS_APP_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXTJS_APP_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXTJS_APP_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXTJS_APP_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXTJS_APP_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXTJS_APP_FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXTJS_APP_LOCAL: process.env.NEXT_PUBLIC_APP_LOCAL,
  PROXY: process.env.NEXT_PUBLIC_APP_PROXY,
};
