import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './provider';
import Navigation from '../layouts/navigation/layout';
import Footer from '../layouts/footer/layout';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'AnimeWorld',
  description: 'Generated by Duy Bao',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='dark text-foreground bg-background'>
        <Providers>
          <header>
            <Navigation />
          </header>
          <main>{children}</main>
          <footer>
            <Footer></Footer>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
