'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './provider';
import Navigation from './layouts/navigation/layout';
import Footer from './layouts/footer/layout';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body>
        <header>
          <Providers>
            <Navigation />
          </Providers>
        </header>
        <Providers>{children}</Providers>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
